verify changes to GH action that reviews PRs to verify changelogs (#808)
* dummy commit to trigger PR action

* another test commit

* extraneous commit to src

* blah

* update changelog gh action

* another change to the changelog gh action

* update pending-changes to suffice gh action check

* Revert "dummy commit to trigger PR action"

This reverts commit 19d2f679457997ef56b385a4009eb233a22fc3dd.

* Revert "another test commit"

This reverts commit 7eff82b7550a346e0019b2844d9caac1afe022c3.

* Revert "extraneous commit to src"

This reverts commit d67a6e558e0e6b266ec01f87af062ca0b275919c.

* Revert "blah"

This reverts commit 384af8bcab4529821456e2d59a6c40e80c483b39.

* Revert "update pending-changes to suffice gh action check"

This reverts commit 2c8c6d969e3c2ccc4e5208d034cb832d8026c662.

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -16,6 +16,13 @@ jobs:
           node-version: 14
       - run: |
           echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
+          # git diff --quiet leads to no output and an exit code based on the result
+          # when there are no diffs, the exit code is 0 (true)
+          # when there are diffs, the exit code is 1 (false)
+          if git diff --quiet HEAD~ pending-changes.yaml; then
+            echo No updates to pending-changes.yaml detected. Add an entry to this file for the relevant SDKs as part of this PR
+            exit 1
+          fi
           cd packages/
           packages=$(git diff HEAD~ --name-only | cut -d "/" -f 2 | uniq)
           for package in $packages; do
